# Generated by Django 4.2.7 on 2023-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='fullname')),
                ('email', models.EmailField(max_length=100, verbose_name='companyemail')),
            ],
            options={
                'db_table': 'checkedUsers',
            },
        ),
    ]
